version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/fintrack
      - JWT_SECRET=my_ultra_secret_key_12345
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend